### ISSUE TITLE
500 Internel Server Error

### ISSUE THREAD

**Issue by maljolani** [stpl/csv_import_issues#21]
Dear,

When I am trying to upload the sample file to import it, i face the following 500 error, 

```
Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back
```

When I check the production logs i found the following,

```
Started POST "/projects/service-desk/csv_imports" for 192.168.10.53 at 2015-10-12 08:04:50 +0000
Processing by CsvImportsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"7Wy776UqQ2I/XlyV3ogF+rgmtxM6632AiKZiJCm73ZnwCiFwWL/wXWtGug/LlmbUJmITlxJdVejumyFNI3pInw==", "csv_import"=>{"csv"=>#<ActionDispatch::Http::UploadedFile:0x00000007cdd460 @tempfile=#<File:/tmp/RackMultipart20151012-31972-1rwm5jn.csv>, @original_filename="sample.csv", @content_type="text/csv", @headers="Content-Disposition: form-data; name=\"csv_import[csv]\"; filename=\"sample.csv\"\r\nContent-Type: text/csv\r\n">}, "commit"=>"Import CSV", "project_id"=>"service-desk"}
  Current user: mohammad.aljolani (id=9)
Completed 500 Internal Server Error in 122ms (ActiveRecord: 9.5ms)

NoMethodError (undefined method `call' for "result == false":String):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode
```

I have redmine 3 installed, also i followed the instlation instruction and it should be installed successfully

**Comment by hosseio** [comment]
+1

**Comment by fastuser** [comment]
+1 -See "Internal Error"

**Comment by johnp2686** [comment]
I have redmine 3.1.1 installed, also i followed the instlation instruction and it should be installed successfully but same error occured

**Comment by tianxiaxi** [comment]
I use csv_import_issues on redmine 3.0.1, also got this error:

```
NoMethodError (undefined method `call' for "result == false":String):
  activesupport (4.2.0) lib/active_support/callbacks.rb:164:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_csv_post_process_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  paperclip (3.5.2) lib/paperclip/callbacks.rb:26:in `run_paperclip_callbacks'
  paperclip (3.5.2) lib/paperclip/attachment.rb:414:in `block in post_process'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_post_process_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  paperclip (3.5.2) lib/paperclip/callbacks.rb:26:in `run_paperclip_callbacks'
  paperclip (3.5.2) lib/paperclip/attachment.rb:413:in `post_process'
  paperclip (3.5.2) lib/paperclip/attachment.rb:112:in `assign'
  paperclip (3.5.2) lib/paperclip/has_attached_file.rb:65:in `block in define_setter'
  plugins/csv_import_issues/app/models/csv_import.rb:18:in `block in initialize'
  actionpack (4.2.0) lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
  actionpack (4.2.0) lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
  plugins/csv_import_issues/app/models/csv_import.rb:18:in `initialize'
  plugins/csv_import_issues/app/controllers/csv_imports_controller.rb:38:in `new'
  plugins/csv_import_issues/app/controllers/csv_imports_controller.rb:38:in `validate_csv'
```

**Comment by abhigginbotham** [comment]
+1 Although I see this is old.  Is development still active?

Environment:
  Redmine version                3.0.0.stable
  Ruby version                   2.0.0-p598 (2014-11-13) [x86_64-linux]
  Rails version                  4.2.0
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.10
  Git                            1.9.5
  Filesystem  
Redmine plugins:
  csv_import_issues              0.0.2
  redmine_dmsf                   1.5.3

Processing by CsvImportsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"UMG2uNpiFPJ3p9jKdOTkTlz2uGcekIq+YQuyp0E1ZRxnanousgm2m2YqY5kck2A92mPsBIrWTKOpNkiCuSrjEg==", "csv_import"=>{"csv"=>#<ActionDispatch::Http::UploadedFile:0x007f4ce991f900 @tempfile=#<Tempfile:/tmp/RackMultipart20151120-20105-r21bkl.csv>, @original_filename="sample.csv", @content_type="application/vnd.ms-excel", @headers="Content-Disposition: form-data; name=\"csv_import[csv]\"; filename=\"sample.csv\"\r\nContent-Type: application/vnd.ms-excel\r\n">}, "commit"=>"Import CSV", "project_id"=>"ldm"}

Completed 500 Internal Server Error in 28ms

NoMethodError (undefined method `call' for "result == false":String):
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:164:in`block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in`_run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_csv_post_process_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in`run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/paperclip-3.5.2/lib/paperclip/callbacks.rb:26:in `run_paperclip_callbacks'
  vendor/bundle/ruby/2.0.0/gems/paperclip-3.5.2/lib/paperclip/attachment.rb:414:in`block in post_process'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in`_run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_post_process_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in`run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/paperclip-3.5.2/lib/paperclip/callbacks.rb:26:in `run_paperclip_callbacks'
  vendor/bundle/ruby/2.0.0/gems/paperclip-3.5.2/lib/paperclip/attachment.rb:413:in`post_process'
  vendor/bundle/ruby/2.0.0/gems/paperclip-3.5.2/lib/paperclip/attachment.rb:112:in `assign'
  vendor/bundle/ruby/2.0.0/gems/paperclip-3.5.2/lib/paperclip/has_attached_file.rb:65:in`block in define_setter'
  plugins/csv_import_issues/app/models/csv_import.rb:18:in `block in initialize'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/strong_parameters.rb:183:in`each_pair'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/strong_parameters.rb:183:in `each_pair'
  plugins/csv_import_issues/app/models/csv_import.rb:18:in`initialize'
  plugins/csv_import_issues/app/controllers/csv_imports_controller.rb:38:in `new'
  plugins/csv_import_issues/app/controllers/csv_imports_controller.rb:38:in`validate_csv'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:427:in `block in make_lambda'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:145:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:145:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:234:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:169:in `block in halting'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in`_run_process_action_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/abstract_controller/callbacks.rb:19:in`process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:31:in`block in process_action'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `block in instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/notifications.rb:164:in `instrument'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/instrumentation.rb:30:in`process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/abstract_controller/base.rb:137:in `process'
  vendor/bundle/ruby/2.0.0/gems/actionview-4.2.0/lib/action_view/rendering.rb:30:in`process'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal.rb:195:in `dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal/rack_delegation.rb:13:in`dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_controller/metal.rb:236:in `block in action'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:42:in`serve'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:43:in `block in serve'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in`each'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/journey/router.rb:30:in `serve'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:802:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-openid-1.4.2/lib/rack/openid.rb:98:in `call'
  vendor/bundle/ruby/2.0.0/gems/request_store-1.0.5/lib/request_store/middleware.rb:9:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-xml_parser-1.0.2/lib/action_dispatch/xml_params_parser.rb:16:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  plugins/redmine_dmsf/lib/redmine_dmsf/webdav/no_parse.rb:33:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/flash.rb:260:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in`context'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/cookies.rb:560:in`call'
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/query_cache.rb:36:in `call'
  vendor/bundle/ruby/2.0.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in`_run_call_callbacks'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in`call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:38:in`call_app'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in`block in tagged'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in`tagged'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in`call'
  vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in`call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in`call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in`public_send'
  vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in`block in call'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
  vendor/bundle/ruby/2.0.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in`call'
  passenger (4.0.57) lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  passenger (4.0.57) lib/phusion_passenger/request_handler/thread_handler.rb:141:in`accept_and_process_next_request'
  passenger (4.0.57) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.57) lib/phusion_passenger/request_handler.rb:455:in`block (3 levels) in start_threads'
