### ISSUE TITLE
Internal error when I click "Import from CSV"

### ISSUE THREAD

**Issue by kuzminvv** [stpl/csv_import_issues#3]
Hello,

I'm using redmine 2.5.0.stable at virtual appliance from bitnami and when I click on link "Import from CSV", I get:

Internal error

An error occurred on the page you were trying to access.
If you continue to experience problems please contact your Redmine administrator for assistance.

If you are the Redmine administrator, check your log files for details about the error.

Back

---

and at log:

Started GET "/redmine/projects/sales/csv_imports/new" for 192.168.6.254 at 2014-04-10 13:59:28 +0400
Processing by CsvImportsController#new as HTML
  Parameters: {"project_id"=>"sales"}
  Current user: kuzminvv (id=1)
  Rendered plugins/csv_import_issues/app/views/csv_imports/new.html.erb within layouts/base (3.1ms)
Completed 500 Internal Server Error in 17.6ms

ActionView::Template::Error (undefined method `persisted?' for #<CsvImport:0x007fe14d1ac850>):
    12:       </ul>
    13:   </div>
    14: <% end %>
    15: <%= form_for @import, :url=> project_csv_imports_path, :html => {:class=>"tabular"} do |f| %>
    16:   <div class="box">
    17:     <p>
    18:       <label>File</label>
  vendor/bundle/ruby/1.9.1/gems/activemodel-3.2.17/lib/active_model/conversion.rb:46:in`to_key'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/record_identifier.rb:76:in `record_key_for_dom_id'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/record_identifier.rb:57:in`dom_id'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/form_helper.rb:391:in `apply_form_for_options!'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/helpers/form_helper.rb:370:in`form_for'
  plugins/csv_import_issues/app/views/csv_imports/new.html.erb:15:in `_plugins_csv_import_issues_app_views_csv_imports_new_html_erb___2432329326864418436_70302819013080'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:145:in`block in render'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:125:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/template.rb:143:in`render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in`block in instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `block in instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:54:in`render_with_layout'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/template_renderer.rb:18:in`render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:36:in `render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_view/renderer/renderer.rb:17:in`render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:110:in `_render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/streaming.rb:225:in`_render_template'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:103:in `render_to_body'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/renderers.rb:28:in`render_to_body'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:88:in`render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rendering.rb:16:in `render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:40:in`block (2 levels) in render'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /opt/bitnami/ruby/lib/ruby/1.9.1/benchmark.rb:295:in`realtime'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/core_ext/benchmark.rb:5:in `ms'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:40:in`block in render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railties/controller_runtime.rb:24:in`cleanup_view_runtime'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:39:in `render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/implicit_render.rb:10:in`default_render'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:167:in`process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rendering.rb:10:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:491:in `_run__813960493877402394__process_action__2627050880755799924__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in`__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in`run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/callbacks.rb:17:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rescue.rb:29:in`process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in`block in instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/notifications.rb:123:in`instrument'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/base.rb:121:in`process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/abstract_controller/rendering.rb:45:in `process'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal.rb:203:in`dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_controller/metal.rb:246:in`block in action'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:36:in `call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:68:in`block in call'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in `each'
  vendor/bundle/ruby/1.9.1/gems/journey-1.0.4/lib/journey/router.rb:56:in`call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/routing/route_set.rb:608:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-openid-1.3.1/lib/rack/openid.rb:98:in`call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/etag.rb:23:in`call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/conditionalget.rb:25:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/head.rb:14:in`call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/flash.rb:242:in`call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:210:in `context'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/session/abstract/id.rb:205:in`call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/cookies.rb:341:in `call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/query_cache.rb:64:in`call'
  vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.17/lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in `_run__2021909975888734664__call__1998343459968941363__callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:405:in`__run_callback'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/callbacks.rb:81:in`run_callbacks'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/rack/logger.rb:32:in `call_app'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in`block in call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/tagged_logging.rb:22:in `tagged'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/rack/logger.rb:16:in`call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/request_id.rb:22:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/methodoverride.rb:21:in`call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/runtime.rb:17:in `call'
  vendor/bundle/ruby/1.9.1/gems/activesupport-3.2.17/lib/active_support/cache/strategy/local_cache.rb:72:in`call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/lock.rb:15:in `call'
  vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.17/lib/action_dispatch/middleware/static.rb:63:in`call'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:136:in `forward'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:245:in`fetch'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:185:in `lookup'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:66:in`call!'
  vendor/bundle/ruby/1.9.1/gems/rack-cache-1.2/lib/rack/cache/context.rb:51:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/engine.rb:484:in`call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/application.rb:231:in `call'
  vendor/bundle/ruby/1.9.1/gems/railties-3.2.17/lib/rails/railtie/configurable.rb:30:in`method_missing'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/builder.rb:134:in `call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/urlmap.rb:64:in`block in call'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in `each'
  vendor/bundle/ruby/1.9.1/gems/rack-1.4.5/lib/rack/urlmap.rb:49:in`call'
  passenger (4.0.33) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.33) lib/phusion_passenger/request_handler/thread_handler.rb:141:in`accept_and_process_next_request'
  passenger (4.0.33) lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  passenger (4.0.33) lib/phusion_passenger/request_handler.rb:440:in`block (3 levels) in start_threads'

---

Can you help me?

Environment:
  Redmine version                2.5.0.stable
  Ruby version                   1.9.3-p545 (2014-02-24) [x86_64-linux]
  Rails version                  3.2.17
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.5
  Git                            1.8.5.2
  Filesystem  
Redmine plugins:
  csv_import_issues              0.0.1

**Comment by stpl** [comment]
I have installed bitnami VM and run the plugin. It is working properly and I didn't get any exception.

Please provide more information to debug this.

**Comment by kuzminvv** [comment]
Thanks for your attention for my issue!

I have a new VM from bitnami and I installed the plugin again.
But I get the same internal error.
You can see log file and command line log on this way: http://yadi.sk/d/Amu1N_LYMjTnw
What additional information should I provide?

**Comment by tosmatt** [comment]
I get the same internal error.

**Comment by stpl** [comment]
I believe you might be facing this issue because plugin did not got installed properly. Can you follow process listed below:
- Go to installation directory :
  $ cd /installdir/ 
- Setup redmine enviroment :
  $ ./use_redmine
- Go to the Redmine plugins directory:
  $ cd apps/redmine/htdocs/plugins
- Download the latest plugin
  $ git clone https://github.com/stpl/csv_import_issues
- Run below command :
  $ bundle install --without development test --no-deployment
- Restart Redmine
  $ /installdir/ctlscript.sh restart

After this plugin should work. Please let me know if issue still persist.

You can refer this link:- http://wiki.bitnami.com/Applications/BitNami_Redmine#How_to_install_Redmine_People_plugin.3f

**Comment by sacbalz** [comment]
I had the same problem with the bitnami vm. Here's what I did to get it working.
add plugin
https://github.com/stpl/csv_import_issues
Download Zip
use winscp to copy to /opt/bitnami/apps/redmine/htdocs/plugins
unzip, mv csv_import_issues_master csv_import_issues
cd /opt/bitnami
./use_redmine
cd apps/redmine/htdocs
bundle install --without development test postgresql sqlite --no-deployment
bundle install --without development test postgresql sqlite --deployment
ruby bin/rake redmine:plugins RAILS_ENV=production
sudo /opt/bitnami/ctlscript.sh restart

**Comment by xdomingo** [comment]
Many thanks sacbalz, your instructions worked like a charm :-)

**Comment by stpl** [comment]
Hi @sacbalz ,

Can you please try to follow the exact steps which we mentioned above?

As I can see that you have executed the commands from different directories which might affect plugin installation process.
